[features]
seeds = false
skip-lint = false

[programs.localnet]
token_contract = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
token_contract = "3HDzVJmy9RpkBCaMnQK8BFsjMuJJLY4VfneuRX4DH4Ha"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/kaz/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
